#!/usr/bin/env bash

cd /root/werbot || { echo "Failed to enter the directory => /root/werbot"; exit 1; }

werbot(){
  case "$1" in
    "--help")
      sudo bash werbot.sh 
      ;;
    "--server")
      server 
      ;;
    "--phish")
      host
      ;;
    *)
      echo "Erro! Unknown command: $1"
      exit 1
      ;;
  esac
}

server(){
  echo "[::] Starting servidor..."
  npm run server 
}

host(){
  echo "[::] Starting phishing..."
   npm run phish
}

werbot "$@"

